// @flow
import { createActions } from 'redux-actions';
import AdminActionTypes from '../constants/adminActionTypes';

export const {
  getCategoryAdminData,
  saveCategoryAdminData,
  newCategoryAdminData,
  updateCategoryAdminData,
  categoryAdminSelectedData,
  saveCategoryAdminSelectedData,
  deleteCategoryAdminData,
  saveDeleteCategoryAdminData,
  resetPasswordAdmin,
  saveDeleteUserAdminData,
  getGenresAdminData,
  saveGenresAdminData,
  newGenresAdminData,
  updateGenresAdminData,
  genresAdminSelectedData,
  saveGenresAdminSelectedData,
  deleteGenresAdminData,
  saveDeleteGenresAdminData,
  getLevelAdminData,
  saveLevelAdminData,
  newLevelAdminData,
  updateLevelAdminData,
  levelAdminSelectedData,
  saveLevelAdminSelectedData,
  deleteLevelAdminData,
  saveDeleteLevelAdminData,
  getMoviesAdminData,
  saveMoviesAdminData,
  newMoviesAdminData,
  updateMoviesAdminData,
  moviesAdminSelectedData,
  saveMoviesAdminSelectedData,
  deleteMoviesAdminData,
  saveDeleteMoviesAdminData,
  getAllCategoryAdminData,
  getAllGenresAdminData,
  getAllLevelAdminData,

  getSubtitlesAdminData,
  saveSubtitlesAdminData,
  newSubtitlesAdminData,
  updateSubtitlesAdminData,
  subtitlesAdminSelectedData,
  saveSubtitlesAdminSelectedData,
  deleteSubtitlesAdminData,
  saveDeleteSubtitlesAdminData,

  getAllMoviesAdminData,
} = createActions({
  [AdminActionTypes.GET_CATEGORY_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.SAVE_CATEGORY_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.NEW_CATEGORY_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.UPDATE_CATEGORY_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.CATEGORY_ADMIN_SELECTED_DATA]: payload => payload,
  [AdminActionTypes.SAVE_CATEGORY_ADMIN_SELECTED_DATA]: payload => payload,
  [AdminActionTypes.DELETE_CATEGORY_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.SAVE_DELETE_CATEGORY_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.RESET_PASSWORD_ADMIN]: payload => payload,
  [AdminActionTypes.SAVE_DELETE_USER_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.GET_GENRES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.SAVE_GENRES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.NEW_GENRES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.UPDATE_GENRES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.GENRES_ADMIN_SELECTED_DATA]: payload => payload,
  [AdminActionTypes.SAVE_GENRES_ADMIN_SELECTED_DATA]: payload => payload,
  [AdminActionTypes.DELETE_GENRES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.SAVE_DELETE_GENRES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.GET_LEVEL_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.SAVE_LEVEL_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.NEW_LEVEL_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.UPDATE_LEVEL_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.LEVEL_ADMIN_SELECTED_DATA]: payload => payload,
  [AdminActionTypes.SAVE_LEVEL_ADMIN_SELECTED_DATA]: payload => payload,
  [AdminActionTypes.DELETE_LEVEL_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.SAVE_DELETE_LEVEL_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.GET_MOVIES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.SAVE_MOVIES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.NEW_MOVIES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.UPDATE_MOVIES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.MOVIES_ADMIN_SELECTED_DATA]: payload => payload,
  [AdminActionTypes.SAVE_MOVIES_ADMIN_SELECTED_DATA]: payload => payload,
  [AdminActionTypes.DELETE_MOVIES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.SAVE_DELETE_MOVIES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.SAVE_NEW_MOVIES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.GET_ALL_CATEGORY_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.GET_ALL_GENRES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.GET_ALL_LEVEL_ADMIN_DATA]: payload => payload,

  [AdminActionTypes.GET_SUBTITLES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.SAVE_SUBTITLES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.NEW_SUBTITLES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.UPDATE_SUBTITLES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.SUBTITLES_ADMIN_SELECTED_DATA]: payload => payload,
  [AdminActionTypes.SAVE_SUBTITLES_ADMIN_SELECTED_DATA]: payload => payload,
  [AdminActionTypes.DELETE_SUBTITLES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.SAVE_DELETE_SUBTITLES_ADMIN_DATA]: payload => payload,
  [AdminActionTypes.SAVE_NEW_SUBTITLES_ADMIN_DATA]: payload => payload,

  [AdminActionTypes.GET_ALL_MOVIES_ADMIN_DATA]: payload => payload,

});
