// @flow
import { createActions } from 'redux-actions';
import ActionsTypes from '../constants/actionTypes';

export const {
  login,
  loginUserData,
  logout,
  logoutUserData,
  signup,
  getFilmData,
  saveFilmData,
  getHotFilmData,
  saveHotFilmData,
  getFilmPaginateData,
  saveFilmPaginateData,
  getFilmByLevelData,
  saveFilmByLevelData,
  getLevelData,
  saveLevelData,
  getCategoryData,
  saveCategoryData,
  getSelectedFilmData,
  saveSelectedFilmData,
  getFilmEpisodeData,
  saveFilmEpisodeData,
  getTranslateTextData,
  saveTranslateTextData,
  getListUserData,
  saveListUserData,
  deleteUserData,
  newUserData,
  saveUserData,
  editUserData,
  showUserData,
  updateUserData,
  markVocabularyData,
  saveVocabularyData,
  getTextSpeechData,
  saveTextSpeechData,
  getRemindVocabularyData,
  saveRemindVocabularyData,
  saveIsRemindData,
  getCommentData,
  saveCommentData,
  addCommentData,
  saveNewCommentData,
  editCommentData,
  saveEditCommentData,
  saveModalSelectedData,
  deleteCommentData,
  saveDeleteCommentData,
  getNotificationData,
  saveNotificationData,
  readNotificationData,
  saveReadNotificationData,
  ratingMovieData,
  getCurrentRateData,
  saveCurrentRateData,
  getCategoryFilmData,
  saveCategoryFilmData,
  getVocabularyTestData,
  saveVocabularyTestData,
  getNextRemindVocabularyData,
  saveNextRemindVocabularyData,
} = createActions({
  [ActionsTypes.LOGIN]: payload => payload,
  [ActionsTypes.LOGIN_USER_DATA]: user => ({ user }),
  [ActionsTypes.LOGOUT]: payload => payload,
  [ActionsTypes.LOGOUT_USER_DATA]: payload => payload,
  [ActionsTypes.SIGNUP]: payload => payload,
  [ActionsTypes.GET_FILM_DATA]: payload => payload,
  [ActionsTypes.SAVE_FILM_DATA]: payload => payload,
  [ActionsTypes.GET_HOT_FILM_DATA]: payload => payload,
  [ActionsTypes.SAVE_HOT_FILM_DATA]: payload => payload,
  [ActionsTypes.GET_FILM_PAGINATE_DATA]: payload => payload,
  [ActionsTypes.SAVE_FILM_PAGINATE_DATA]: payload => payload,
  [ActionsTypes.GET_FILM_BY_LEVEL_DATA]: payload => payload,
  [ActionsTypes.SAVE_FILM_BY_LEVEL_DATA]: payload => payload,
  [ActionsTypes.GET_LEVEL_DATA]: payload => payload,
  [ActionsTypes.SAVE_LEVEL_DATA]: payload => payload,
  [ActionsTypes.GET_CATEGORY_DATA]: payload => payload,
  [ActionsTypes.SAVE_CATEGORY_DATA]: payload => payload,
  [ActionsTypes.GET_SELECTED_FILM_DATA]: payload => payload,
  [ActionsTypes.SAVE_SELECTED_FILM_DATA]: payload => payload,
  [ActionsTypes.GET_FILM_EPISODE_DATA]: payload => payload,
  [ActionsTypes.SAVE_FILM_EPISODE_DATA]: payload => payload,
  [ActionsTypes.GET_TRANSLATE_TEXT_DATA]: payload => payload,
  [ActionsTypes.SAVE_TRANSLATE_TEXT_DATA]: payload => payload,
  [ActionsTypes.GET_LIST_USER_DATA]: payload => payload,
  [ActionsTypes.SAVE_LIST_USER_DATA]: payload => payload,
  [ActionsTypes.DELETE_USER_DATA]: payload => payload,
  [ActionsTypes.NEW_USER_DATA]: payload => payload,
  [ActionsTypes.SAVE_USER_DATA]: payload => payload,
  [ActionsTypes.EDIT_USER_DATA]: payload => payload,
  [ActionsTypes.SHOW_USER_DATA]: payload => payload,
  [ActionsTypes.UPDATE_USER_DATA]: payload => payload,
  [ActionsTypes.MARK_VOCABULARY_DATA]: payload => payload,
  [ActionsTypes.SAVE_VOCABULARY_DATA]: payload => payload,
  [ActionsTypes.GET_TEXT_SPEECH_DATA]: payload => payload,
  [ActionsTypes.SAVE_TEXT_SPEECH_DATA]: payload => payload,
  [ActionsTypes.GET_REMIND_VOCABULARY_DATA]: payload => payload,
  [ActionsTypes.SAVE_REMIND_VOCABULARY_DATA]: payload => payload,
  [ActionsTypes.SAVE_IS_REMIND_DATA]: payload => payload,
  [ActionsTypes.GET_COMMENT_DATA]: payload => payload,
  [ActionsTypes.SAVE_COMMENT_DATA]: payload => payload,
  [ActionsTypes.ADD_COMMENT_DATA]: payload => payload,
  [ActionsTypes.SAVE_NEW_COMMENT_DATA]: payload => payload,
  [ActionsTypes.EDIT_COMMENT_DATA]: payload => payload,
  [ActionsTypes.SAVE_EDIT_COMMENT_DATA]: payload => payload,
  [ActionsTypes.SAVE_MODAL_SELECTED_DATA]: payload => payload,
  [ActionsTypes.DELETE_COMMENT_DATA]: payload => payload,
  [ActionsTypes.SAVE_DELETE_COMMENT_DATA]: payload => payload,
  [ActionsTypes.GET_NOTIFICATION_DATA]: payload => payload,
  [ActionsTypes.SAVE_NOTIFICATION_DATA]: payload => payload,
  [ActionsTypes.READ_NOTIFICATION_DATA]: payload => payload,
  [ActionsTypes.SAVE_READ_NOTIFICATION_DATA]: payload => payload,
  [ActionsTypes.RATING_MOVIE_DATA]: payload => payload,
  [ActionsTypes.GET_CURRENT_RATE_DATA]: payload => payload,
  [ActionsTypes.SAVE_CURRENT_RATE_DATA]: payload => payload,
  [ActionsTypes.GET_CATEGORY_FILM_DATA]: payload => payload,
  [ActionsTypes.SAVE_CATEGORY_FILM_DATA]: payload => payload,
  [ActionsTypes.GET_VOCABULARY_TEST_DATA]: payload => payload,
  [ActionsTypes.SAVE_VOCABULARY_TEST_DATA]: payload => payload,
  [ActionsTypes.GET_NEXT_REMIND_VOCABULARY_DATA]: payload => payload,
  [ActionsTypes.SAVE_NEXT_REMIND_VOCABULARY_DATA]: payload => payload,
});
