// eslint-disable-next-line import/no-extraneous-dependencies
import keyMirror from 'fbjs/lib/keyMirror';

const ActionTypes = keyMirror({
  LOGIN: undefined,
  LOGIN_USER_DATA: undefined,
  LOGOUT: undefined,
  LOGOUT_USER_DATA: undefined,
  SIGNUP: undefined,
  GET_FILM_DATA: undefined,
  SAVE_FILM_DATA: undefined,
  GET_HOT_FILM_DATA: undefined,
  SAVE_HOT_FILM_DATA: undefined,
  GET_FILM_PAGINATE_DATA: undefined,
  SAVE_FILM_PAGINATE_DATA: undefined,
  GET_FILM_BY_LEVEL_DATA: undefined,
  SAVE_FILM_BY_LEVEL_DATA: undefined,
  GET_LEVEL_DATA: undefined,
  SAVE_LEVEL_DATA: undefined,
  GET_CATEGORY_DATA: undefined,
  SAVE_CATEGORY_DATA: undefined,
  GET_SELECTED_FILM_DATA: undefined,
  SAVE_SELECTED_FILM_DATA: undefined,
  GET_FILM_EPISODE_DATA: undefined,
  SAVE_FILM_EPISODE_DATA: undefined,
  GET_TRANSLATE_TEXT_DATA: undefined,
  SAVE_TRANSLATE_TEXT_DATA: undefined,
  GET_LIST_USER_DATA: undefined,
  SAVE_LIST_USER_DATA: undefined,
  DELETE_USER_DATA: undefined,
  NEW_USER_DATA: undefined,
  SAVE_USER_DATA: undefined,
  CHECK_EMAIL_EXIST: undefined,
  EDIT_USER_DATA: undefined,
  SHOW_USER_DATA: undefined,
  UPDATE_USER_DATA: undefined,
  MARK_VOCABULARY_DATA: undefined,
  SAVE_VOCABULARY_DATA: undefined,
  GET_TEXT_SPEECH_DATA: undefined,
  SAVE_TEXT_SPEECH_DATA: undefined,
  GET_REMIND_VOCABULARY_DATA: undefined,
  SAVE_REMIND_VOCABULARY_DATA: undefined,
  SAVE_IS_REMIND_DATA: undefined,
  SAVE_MODAL_SELECTED_DATA: undefined,
  GET_COMMENT_DATA: undefined,
  SAVE_COMMENT_DATA: undefined,
  ADD_COMMENT_DATA: undefined,
  SAVE_NEW_COMMENT_DATA: undefined,
  EDIT_COMMENT_DATA: undefined,
  SAVE_EDIT_COMMENT_DATA: undefined,
  DELETE_COMMENT_DATA: undefined,
  SAVE_DELETE_COMMENT_DATA: undefined,
  GET_NOTIFICATION_DATA: undefined,
  SAVE_NOTIFICATION_DATA: undefined,
  READ_NOTIFICATION_DATA: undefined,
  SAVE_READ_NOTIFICATION_DATA: undefined,
  RATING_MOVIE_DATA: undefined,
  GET_CURRENT_RATE_DATA: undefined,
  SAVE_CURRENT_RATE_DATA: undefined,
  GET_CATEGORY_FILM_DATA: undefined,
  SAVE_CATEGORY_FILM_DATA: undefined,
  GET_VOCABULARY_TEST_DATA: undefined,
  SAVE_VOCABULARY_TEST_DATA: undefined,
  GET_NEXT_REMIND_VOCABULARY_DATA: undefined,
  SAVE_NEXT_REMIND_VOCABULARY_DATA: undefined,
});

export default ActionTypes;
